/**
 * Preset chart states for the guided story sections. Each preset describes the
 * evidence view readers should see when a section becomes active.
 */

export const DEFAULT_STORY_PRESET_ID = "real-economy";

export const STORY_PRESETS = {
  "real-economy": {
    axis: "GDP",
    year: 2023,
    viewMode: "map",
    selectionMode: "regions",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific", "Latin America"],
    selectedIso3: ["DEU", "FRA", "GBR", "USA", "JPN"],
    treemapSnapshot: "latest",
    stageFocus: "top",
    callout: {
      label: "Act 1 evidence",
      title: "Europe still grew.",
      body: "The map is set to compounded regional GDP growth in 2023. Europe is not flat: it is 1.38x its 2000 GDP baseline in this dataset.",
      stats: ["Compounded since 2000", "Regions selected", "2023"],
    },
  },
  "us-eu-frame": {
    axis: "GDP per Capita",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America"],
    selectedIso3: ["USA", "CHE", "DEU", "FRA", "GBR"],
    treemapSnapshot: "latest",
    mapFocus: "north-atlantic",
    stageFocus: "top",
    callout: {
      label: "Act 2 evidence",
      title: "This is the benchmark.",
      body: "The graph zooms into North America and Europe and switches to countries, so Canada no longer hides the US path inside a regional average.",
      stats: ["Compounded since 2000", "Country-level view", "GDP per capita"],
    },
  },
  "divergence-hypothesis": {
    axis: "ETF Price",
    year: 2023,
    viewMode: "scatter",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["DEU", "GBR", "USA", "KOR", "JPN"],
    treemapSnapshot: "latest",
    stageFocus: "top",
    callout: {
      label: "Act 2.5 evidence",
      title: "The market proxy separates.",
      body: "Scatter mode compares GDP per capita growth with ETF growth. The US sits far above major European markets on the ETF axis.",
      stats: ["ETF Price", "Scatter view", "Selected outliers"],
    },
  },
  "europe-dispersion": {
    axis: "ETF Price",
    year: 2023,
    viewMode: "scatter",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe"],
    selectedIso3: ["DEU", "FRA", "GBR", "CHE", "NLD"],
    treemapSnapshot: "latest",
    stageFocus: "top",
    callout: {
      label: "Act 3 evidence",
      title: "Europe spreads out.",
      body: "The selection now focuses on European countries, showing why the average cannot explain every national path.",
      stats: ["Europe only", "Country selection", "Scatter view"],
    },
  },
  "sector-drivers": {
    axis: "Market Cap",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["USA", "JPN", "GBR", "KOR", "DEU"],
    treemapSnapshot: "latest",
    stageFocus: "treemap",
    callout: {
      label: "Act 4 evidence",
      title: "Index weight follows sectors.",
      body: "The view jumps to ACWI composition, where US country weight and information technology dominate the latest snapshot.",
      stats: ["ACWI", "Latest snapshot", "Sector lens"],
    },
  },
  "wrap-up": {
    axis: "GDP per Capita",
    year: 2023,
    viewMode: "scatter",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["DEU", "FRA", "GBR", "USA", "KOR"],
    treemapSnapshot: "latest",
    stageFocus: "top",
    callout: {
      label: "Conclusion evidence",
      title: "The answer depends on the metric.",
      body: "The explorer returns to the broad comparison: output growth remains visible, while market-linked indicators show the sharper divergence.",
      stats: ["GDP per capita", "ETF contrast", "Audit the claim"],
    },
  },
  /*
   * Earlier preset draft retained while the final story uses the whiteboard arc
   * above. These remain available for quick restoration or appendix views.
  "market-gap": {
    axis: "ETF Price",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["DEU", "GBR", "USA", "KOR", "JPN"],
    treemapSnapshot: "latest",
    stageFocus: "top",
  },
  "scatter-gap": {
    axis: "ETF Price",
    year: 2023,
    viewMode: "scatter",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["DEU", "GBR", "USA", "KOR", "CHE"],
    treemapSnapshot: "latest",
    stageFocus: "top",
  },
  "market-cap": {
    axis: "Market Cap",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["KOR", "USA", "DEU", "GBR", "ITA"],
    treemapSnapshot: "latest",
    stageFocus: "top",
  },
  */
  "acwi-latest": {
    axis: "Market Cap",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["USA", "JPN", "GBR", "KOR", "DEU"],
    treemapSnapshot: "latest",
    stageFocus: "treemap",
    callout: {
      label: "ACWI evidence",
      title: "Latest index structure.",
      body: "The latest ACWI snapshot shows how much global equity exposure now depends on the US and technology-heavy sectors.",
      stats: ["Latest ACWI", "US weight", "Tech weight"],
    },
  },
  "acwi-first": {
    axis: "Market Cap",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["USA", "JPN", "GBR", "KOR", "DEU"],
    treemapSnapshot: "first",
    stageFocus: "treemap",
    callout: {
      label: "ACWI evidence",
      title: "Earlier index structure.",
      body: "The first ACWI snapshot provides the baseline before the latest US and technology concentration.",
      stats: ["2015 ACWI", "Baseline", "Country weights"],
    },
  },
  explore: {
    axis: "GDP",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific", "Latin America"],
    selectedIso3: ["DEU", "FRA", "GBR", "USA", "JPN"],
    treemapSnapshot: "latest",
    stageFocus: "top",
    callout: {
      label: "Explorer",
      title: "Test the story yourself.",
      body: "Change the indicator, year, geography, and scale to see whether the claim holds beyond the guided sequence.",
      stats: ["Manual controls", "All indicators", "Open exploration"],
    },
  },
};
