/**
 * Preset chart states for the guided story sections. Each preset describes the
 * evidence view readers should see when a section becomes active.
 */

export const DEFAULT_STORY_PRESET_ID = "real-economy";

export const STORY_PRESETS = {
  "real-economy": {
    axis: "GDP",
    year: 2023,
    viewMode: "map",
    selectionMode: "regions",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe", "North America", "Asia-Pacific", "Latin America"],
    selectedIso3: ["DEU", "FRA", "GBR", "USA", "JPN"],
    treemapSnapshot: "latest",
    stageSteps: ["stage-map", "stage-trajectory"],
    stageFocus: "stage-map",
    callout: {
      label: "Act 1 evidence",
      title: "The regional view rules out collapse.",
      body: "Europe stays above its 2000 baseline on both GDP and GDP per capita. The rest of the story is about relative pace and market outcomes, not whether Europe stopped growing outright.",
      stats: ["GDP and GDP/person > 1x", "Regional comparison", "2023"],
    },
  },
  "us-eu-frame": {
    axis: "GDP per Capita",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe", "North America"],
    selectedIso3: ["USA", "CHE", "DEU", "FRA", "GBR"],
    treemapSnapshot: "latest",
    mapFocus: "north-atlantic",
    stageSteps: ["stage-map"],
    stageFocus: "stage-map",
    callout: {
      label: "Act 2 evidence",
      title: "The comparison frame is deliberate.",
      body: "From this point on, the chart holds Europe and North America as rich-market peers at country level. That keeps the rest of the story focused on within-peer divergence rather than global catch-up.",
      stats: ["Rich-market peers", "Country-level frame", "Rest of story"],
    },
  },
  "divergence-hypothesis": {
    axis: "ETF Price",
    year: 2023,
    viewMode: "scatter",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["DEU", "GBR", "USA", "KOR", "JPN"],
    treemapSnapshot: "latest",
    stageSteps: ["stage-evolution"],
    stageFocus: "stage-evolution",
    calloutPlacement: "inline",
    callout: {
      label: "Act 3 evidence",
      title: "The break clusters around 2008.",
      body: "Candidate break years concentrate around the crisis window, and the normalization explorer lets you test how much the split changes with the base year, lens, and price adjustment.",
      stats: ["Break-year test", "Normalization explorer", "Lens-sensitive gap"],
    },
  },
  "europe-dispersion": {
    axis: "ETF Price",
    year: 2023,
    viewMode: "scatter",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe"],
    selectedIso3: ["DEU", "FRA", "GBR", "CHE", "NLD", "USA"],
    treemapSnapshot: "latest",
    stageSteps: ["stage-map", "stage-trajectory"],
    stageFocus: "stage-map",
    callout: {
      label: "Act 4 evidence",
      title: "Europe spreads out, but the US still clears the cluster.",
      body: "The scatter is scoped to the selected comparison set. European ETF outcomes range widely, yet even the strongest selected European exception remains below the US market proxy.",
      stats: ["Selected set only", "Europe + US", "Homogeneity test"],
    },
  },
  "sector-drivers": {
    axis: "Market Cap",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["USA", "JPN", "GBR", "KOR", "DEU"],
    treemapSnapshot: "latest",
    stageSteps: ["stage-acwi"],
    stageFocus: "stage-acwi",
    callout: {
      label: "Act 5 evidence",
      title: "Index weight follows sectors.",
      body: "The view jumps to ACWI composition, where US country weight and information technology dominate the latest snapshot.",
      stats: ["ACWI", "Latest snapshot", "Sector lens"],
    },
  },
  "wrap-up": {
    axis: "GDP per Capita",
    year: 2023,
    viewMode: "scatter",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe", "North America"],
    selectedIso3: ["DEU", "FRA", "GBR", "CHE", "NLD", "USA"],
    treemapSnapshot: "latest",
    stageSteps: ["stage-map", "stage-acwi"],
    stageFocus: "stage-map",
    callout: {
      label: "Conclusion evidence",
      title: "Similar output neighborhood, different market outcome.",
      body: "The final scatter is scoped to Europe + US. Selected European GDP per person growth stays near the US, but every selected European ETF proxy sits below the US.",
      stats: ["Europe + US only", "GDP/person close", "ETF gap large"],
    },
  },
  /*
   * Earlier preset draft retained while the final story uses the whiteboard arc
   * above. These remain available for quick restoration or appendix views.
  "market-gap": {
    axis: "ETF Price",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["DEU", "GBR", "USA", "KOR", "JPN"],
    treemapSnapshot: "latest",
    stageFocus: "top",
  },
  "scatter-gap": {
    axis: "ETF Price",
    year: 2023,
    viewMode: "scatter",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["DEU", "GBR", "USA", "KOR", "CHE"],
    treemapSnapshot: "latest",
    stageFocus: "top",
  },
  "market-cap": {
    axis: "Market Cap",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["KOR", "USA", "DEU", "GBR", "ITA"],
    treemapSnapshot: "latest",
    stageFocus: "top",
  },
  */
  "acwi-latest": {
    axis: "Market Cap",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "selected",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["USA", "JPN", "GBR", "KOR", "DEU"],
    treemapSnapshot: "latest",
    stageSteps: ["stage-acwi"],
    stageFocus: "stage-acwi",
    callout: {
      label: "ACWI evidence",
      title: "Latest index structure.",
      body: "The latest ACWI snapshot shows how much global equity exposure now depends on the US and technology-heavy sectors.",
      stats: ["Latest ACWI", "US weight", "Tech weight"],
    },
  },
  "acwi-first": {
    axis: "Market Cap",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    scatterScope: "all",
    selectedRegions: ["Europe", "North America", "Asia-Pacific"],
    selectedIso3: ["USA", "JPN", "GBR", "KOR", "DEU"],
    treemapSnapshot: "first",
    stageSteps: ["stage-acwi"],
    stageFocus: "stage-acwi",
    callout: {
      label: "ACWI evidence",
      title: "Earlier index structure.",
      body: "The first ACWI snapshot provides the baseline before the latest US and technology concentration.",
      stats: ["2015 ACWI", "Baseline", "Country weights"],
    },
  },
  explore: {
    axis: "GDP",
    year: 2023,
    viewMode: "map",
    selectionMode: "countries",
    valueMode: "growth",
    selectedRegions: ["Europe", "North America", "Asia-Pacific", "Latin America"],
    selectedIso3: ["DEU", "FRA", "GBR", "USA", "JPN"],
    treemapSnapshot: "latest",
    stageSteps: ["stage-map"],
    stageFocus: "stage-map",
    callout: {
      label: "Explorer",
      title: "Test the story yourself.",
      body: "Change the indicator, year, geography, and scale to see whether the claim holds beyond the guided sequence.",
      stats: ["Manual controls", "All indicators", "Open exploration"],
    },
  },
};
